/-
Discharging the shared-secret-hiding terms against KEM IND-CPA.

`unlinkAdvantage_ofKEMFull_le` bounds unlinkability by the anonymity advantage
plus two shared-secret-hiding terms. Those terms are exactly the KEM's IND-CPA
(real-or-random shared secret) advantage: the auxiliary announcement data hides
the recipient because the shared secret is pseudorandom.

This file proves that identity, sorry-free, in two steps:

  1. each hiding term is the bias of a real-or-random guessing game -- the KEM
     IND-CPA experiment restricted to the announcement adversary;
  2. that bias equals VCVio's own `KEMScheme.IND_CPA_Advantage` of a concrete
     reduction adversary against the KEM itself. The two experiments draw the
     same independent samples (two keypairs, the hidden bit, the encapsulation,
     an idealized shared secret) in different orders and with one draw left
     unused on one branch; `OracleComp`'s `bind` is a syntactic constructor, so
     neither reordering nor dropping holds on the nose, but both hold after
     `evalDist`, which is all an advantage sees.

Net effect: the shared-secret-hiding half of the unlinkability bound IS a KEM
IND-CPA advantage in VCVio's own formulation, so any bound proved for
`KEMScheme.IND_CPA_Advantage` transfers to it verbatim.

What is NOT proved here, because VCVio does not supply it: a bound on
`KEMScheme.IND_CPA_Advantage` for ML-KEM in terms of MLWE.
`LatticeCrypto/MLKEM/Security.lean` offers `kpke_ind_cpa_security`, which is
about `AsymmEncAlg.IND_CPA_advantage` of K-PKE rather than the KEM, and is
itself `sorry` upstream. `PqStealth/SharedSecretHidingMLWE.lean` records the
exact shape of the missing lemma and specializes the equalities below to
`MLKEM.asKEMScheme`, so that the composition is a one-line `calc` the day the
lemma lands.
-/

import PqStealth.KEMAnonymity
import VCVio.CryptoFoundations.KeyEncapMech

open OracleComp OracleSpec

namespace PqStealth

variable {PK SK C K : Type}

variable {Aux : Type} [SampleableType K]
  (kem : KEM PK SK C K) (auxGen : K → PK → Aux)
  (adv : StealthScheme.UnlinkAdv PK (C × Aux))

/-! ## The concrete VCVio IND-CPA reduction adversary

Built against VCVio's `KeyEncapMech.IND_CPA_Adversary`: the IND-CPA challenge
key is embedded as recipient `b`; the reduction generates the other recipient
itself, then feeds `auxGen(challenge key)` to the unlink distinguisher. Its
`IND_CPA_Advantage` is the corresponding shared-secret-hiding term -- proved
below. -/

/-- IND-CPA reduction adversary for branch `b`. The IND-CPA challenge key is
embedded as recipient `b` and the other recipient is generated by the reduction
itself. The state carries both public keys, because the auxiliary data must be
rebuilt from the same key the real announcement used -- the challenge key. -/
def indCpaAdv (b : Bool) : kem.IND_CPA_Adversary where
  State := PK × PK
  preChallenge pk := do
    let (pk', _) ← kem.keygen
    pure (if b then (pk', pk) else (pk, pk'))
  postChallenge s cStar k := adv s.1 s.2 (cStar, auxGen k (if b then s.2 else s.1))

/-! ## Distribution-level bridges

The reduction games and the real-or-random games differ only in the order of
independent draws and in one draw that a branch ignores. `OracleComp`'s `bind`
is a free-monad constructor, so neither difference is a definitional equality;
both vanish under `evalDist`. -/

section Bridges

/-- An unused uniform draw does not change a computation's output distribution. -/
theorem evalDist_uniformSample_bind_const {α γ : Type} [SampleableType α] (p : ProbComp γ) :
    𝒟[(($ᵗ α) >>= fun _ => p)] = 𝒟[p] := by
  refine evalDist_ext fun x => ?_
  simp only [probOutput_bind_const, probFailure_of_liftM_PMF, tsub_zero, one_mul]

/-- An independent draw may be pulled to the front of a two-step prefix. -/
theorem evalDist_bind_pull_front {α β δ ζ : Type}
    (oa : ProbComp α) (ob : α → ProbComp β) (od : ProbComp δ)
    (k : α → β → δ → ProbComp ζ) :
    𝒟[(do let a ← oa; let b ← ob a; let d ← od; k a b d)] =
      𝒟[(do let d ← od; let a ← oa; let b ← ob a; k a b d)] := by
  calc 𝒟[(do let a ← oa; let b ← ob a; let d ← od; k a b d)]
      = 𝒟[(do let a ← oa; let d ← od; let b ← ob a; k a b d)] := by
        refine evalDist_bind_congr' _ fun a => ?_
        exact evalDist_bind_bind_swap (ob a) od fun b d => k a b d
    _ = 𝒟[(do let d ← od; let a ← oa; let b ← ob a; k a b d)] :=
        evalDist_bind_bind_swap oa od _

/-- Boolean games with the same output distribution have the same bias. -/
theorem boolBiasAdvantage_congr {p q : ProbComp Bool} (h : 𝒟[p] = 𝒟[q]) :
    p.boolBiasAdvantage = q.boolBiasAdvantage := by
  simp only [ProbComp.boolBiasAdvantage, probOutput_def, h]

end Bridges

/-! ## The hiding terms ARE VCVio IND-CPA advantages

Both sides are put in a common normal form: hidden bit first, then the two
keypairs in the order recipient 0, recipient 1, then the challenge
encapsulation, then the idealized shared secret. VCVio's game draws the
challenge keypair first and the hidden bit after the adversary's pre-challenge
phase; the real-or-random game draws the bit first and never draws the
idealized secret on the real branch. Only the keypair swap depends on `b`. -/

/-- Normal form of the branch-`b` reduction game: hidden bit first, the two
keypairs in the order recipient 0, recipient 1, then the challenge
encapsulation to recipient `b`, then the idealized shared secret -- drawn on
both branches of the hidden bit. -/
noncomputable def rorNormalForm (b : Bool) : ProbComp Bool := do
  let hb ← ($ᵗ Bool)
  let pk0 ← kem.keygen
  let pk1 ← kem.keygen
  let ck ← kem.encaps (if b then pk1.1 else pk0.1)
  let kRand ← ($ᵗ K)
  let z ← adv pk0.1 pk1.1
    (ck.1, auxGen (if hb then ck.2 else kRand) (if b then pk1.1 else pk0.1))
  pure (hb == z)

/-- VCVio's IND-CPA game for the branch-`b` reduction adversary is the normal
form. The hidden bit commutes to the front past the whole pre-challenge phase;
on `b = true` the two keypair draws additionally have to be swapped, since
VCVio draws the challenge keypair first and there it is recipient 1's. -/
theorem indCpaGame_eq_evalDist_normalForm (b : Bool) :
    KEMScheme.IND_CPA_Game ProbCompRuntime.probComp (indCpaAdv kem auxGen adv b) =
      𝒟[rorNormalForm kem auxGen adv b] := by
  cases b with
  | true =>
    have hgame : KEMScheme.IND_CPA_Game ProbCompRuntime.probComp
        (indCpaAdv kem auxGen adv true) =
        𝒟[(do
          let pk1 ← kem.keygen
          let pk0 ← kem.keygen
          let hb ← ($ᵗ Bool)
          let ck ← kem.encaps pk1.1
          let kRand ← ($ᵗ K)
          let z ← adv pk0.1 pk1.1 (ck.1, auxGen (if hb then ck.2 else kRand) pk1.1)
          pure (hb == z) : ProbComp Bool)] := by
      simp only [KEMScheme.IND_CPA_Game, indCpaAdv, bind_assoc, pure_bind,
        ProbCompRuntime.probComp, ProbCompRuntime.liftProbComp, ProbCompLift.id]
      rfl
    rw [hgame, evalDist_bind_bind_swap kem.keygen kem.keygen
      (fun pk1 pk0 => do
        let hb ← ($ᵗ Bool)
        let ck ← kem.encaps pk1.1
        let kRand ← ($ᵗ K)
        let z ← adv pk0.1 pk1.1 (ck.1, auxGen (if hb then ck.2 else kRand) pk1.1)
        pure (hb == z))]
    exact evalDist_bind_pull_front kem.keygen (fun _ => kem.keygen) ($ᵗ Bool)
      (fun pk0 pk1 hb => do
        let ck ← kem.encaps pk1.1
        let kRand ← ($ᵗ K)
        let z ← adv pk0.1 pk1.1 (ck.1, auxGen (if hb then ck.2 else kRand) pk1.1)
        pure (hb == z))
  | false =>
    have hgame : KEMScheme.IND_CPA_Game ProbCompRuntime.probComp
        (indCpaAdv kem auxGen adv false) =
        𝒟[(do
          let pk0 ← kem.keygen
          let pk1 ← kem.keygen
          let hb ← ($ᵗ Bool)
          let ck ← kem.encaps pk0.1
          let kRand ← ($ᵗ K)
          let z ← adv pk0.1 pk1.1 (ck.1, auxGen (if hb then ck.2 else kRand) pk0.1)
          pure (hb == z) : ProbComp Bool)] := by
      simp only [KEMScheme.IND_CPA_Game, indCpaAdv, bind_assoc, pure_bind,
        ProbCompRuntime.probComp, ProbCompRuntime.liftProbComp, ProbCompLift.id]
      rfl
    rw [hgame]
    exact evalDist_bind_pull_front kem.keygen (fun _ => kem.keygen) ($ᵗ Bool)
      (fun pk0 pk1 hb => do
        let ck ← kem.encaps pk0.1
        let kRand ← ($ᵗ K)
        let z ← adv pk0.1 pk1.1 (ck.1, auxGen (if hb then ck.2 else kRand) pk0.1)
        pure (hb == z))

variable [DecidableEq Aux]

/-! ## Each hiding term is a real-or-random guessing advantage -/

/-- The shared-secret real-or-random game on branch `b`: guess whether the
auxiliary data was built from the real shared secret (the honest announcement)
or a fresh random key.

Both sides build the auxiliary data from the SAME public key -- recipient `b`'s.
That is what makes this a clean real-or-random KEM question and nothing else;
the separate question of whether the public key itself shows through is carried
by `auxKeyIndependence`. The orientation is VCVio's: the REAL secret sits on
hidden bit `true`, for both values of `b`. -/
noncomputable def rorGame (b : Bool) : ProbComp Bool := do
  let hb ← ($ᵗ Bool)
  let z ← if hb then
      (StealthScheme.ofKEMFull kem auxGen).unlinkSetup >>=
        (StealthScheme.ofKEMFull kem auxGen).unlinkBranch adv b
    else
      (StealthScheme.ofKEMFull kem auxGen).unlinkSetup >>=
        randAuxBranch kem auxGen adv b
  pure (hb == z)

/-- **Sorry-free.** Each shared-secret-hiding term equals the bias of its
real-or-random guessing game -- i.e. it is a KEM IND-CPA advantage. -/
theorem sharedSecretHiding_eq_rorBias (b : Bool) :
    sharedSecretHiding kem auxGen adv b = (rorGame kem auxGen adv b).boolBiasAdvantage := by
  unfold sharedSecretHiding rorGame
  exact (ProbComp.boolBiasAdvantage_eq_boolDistAdvantage_uniformBool_branch _ _).symm

/-- The real-or-random game has the normal form's output distribution: on the
real branch the idealized secret is drawn and ignored. -/
theorem evalDist_rorGame_eq_normalForm (b : Bool) :
    𝒟[rorGame kem auxGen adv b] = 𝒟[rorNormalForm kem auxGen adv b] := by
  unfold rorGame rorNormalForm
  refine evalDist_bind_congr' _ fun hb => ?_
  cases hb with
  | true =>
    simp only [StealthScheme.unlinkSetup, StealthScheme.unlinkBranch,
      StealthScheme.ofKEMFull, bind_assoc, pure_bind, if_true]
    refine evalDist_bind_congr' _ fun pk0 => evalDist_bind_congr' _ fun pk1 =>
      evalDist_bind_congr' _ fun ck => ?_
    exact (evalDist_uniformSample_bind_const _).symm
  | false =>
    simp only [StealthScheme.unlinkSetup, randAuxBranch,
      StealthScheme.ofKEMFull, bind_assoc, pure_bind, Bool.false_eq_true, if_false]

/-- **The glue, proved.** Each shared-secret-hiding term is exactly the VCVio
KEM IND-CPA advantage of the reduction adversary `indCpaAdv … b`. -/
theorem sharedSecretHiding_eq_indCpaAdvantage (b : Bool) :
    sharedSecretHiding kem auxGen adv b =
      KEMScheme.IND_CPA_Advantage ProbCompRuntime.probComp (indCpaAdv kem auxGen adv b) := by
  rw [sharedSecretHiding_eq_rorBias, KEMScheme.IND_CPA_Advantage,
    indCpaGame_eq_evalDist_normalForm,
    boolBiasAdvantage_congr (evalDist_rorGame_eq_normalForm kem auxGen adv b)]
  rfl

/-- **The unlinkability bound with the hiding terms discharged.** Restatement of
`unlinkAdvantage_ofKEMFull_le` in which both shared-secret-hiding terms are KEM
IND-CPA advantages, in VCVio's own formulation, of explicit reduction
adversaries. What is left are the two genuinely non-IND-CPA terms: the auxiliary
data's independence of the recipient's key (the blinding argument) and the KEM's
anonymity. -/
theorem unlinkAdvantage_ofKEMFull_le_indCpa :
    (StealthScheme.ofKEMFull kem auxGen).unlinkAdvantage adv ≤
      KEMScheme.IND_CPA_Advantage ProbCompRuntime.probComp (indCpaAdv kem auxGen adv true)
      + auxKeyIndependence kem auxGen adv
      + kem.anonAdvantage (adv.cipherOf auxGen)
      + KEMScheme.IND_CPA_Advantage ProbCompRuntime.probComp
        (indCpaAdv kem auxGen adv false) := by
  rw [← sharedSecretHiding_eq_indCpaAdvantage, ← sharedSecretHiding_eq_indCpaAdvantage]
  exact unlinkAdvantage_ofKEMFull_le kem auxGen adv

end PqStealth
