[package]
name = "sphincs_c13_verify"
type = "bin"
authors = ["pq-stealth"]
compiler_version = ">=1.0.0"

[dependencies]
keccak256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/keccak256" }
