// Generated by scripts/sync.mjs — do not edit.
export const generatedSidebar = [
  {
    "text": "Key-exchange ERC",
    "items": [
      {
        "text": "Overview",
        "link": "/"
      },
      {
        "text": "Technical reference",
        "link": "/spec/technical-spec"
      },
      {
        "text": "Evidence and proof scope",
        "link": "/spec/erc-evidence"
      },
      {
        "text": "Security boundaries",
        "link": "/spec/security-analysis"
      },
      {
        "text": "Submission roadmap",
        "link": "/research/erc-submission-gap-analysis"
      },
      {
        "text": "Current plan",
        "link": "/overview/plan"
      },
      {
        "text": "Decision log",
        "link": "/spec/decisions"
      },
      {
        "text": "ERC text (human-written)",
        "link": "/spec/erc-draft"
      }
    ]
  },
  {
    "text": "Reference implementations",
    "items": [
      {
        "text": "Python reference",
        "link": "/impl/python"
      },
      {
        "text": "TypeScript client",
        "link": "/impl/js-client"
      }
    ]
  },
  {
    "text": "KEM proof foundations",
    "items": [
      {
        "text": "Proof scope and module map",
        "link": "/lean"
      },
      {
        "text": "Generic announcement model",
        "link": "/lean/announcement-model"
      },
      {
        "text": "KEM anonymity / SPR",
        "link": "/lean/spr-two-hop"
      },
      {
        "text": "Encoding results",
        "link": "/lean/encodings"
      }
    ]
  },
  {
    "text": "Spending and account research",
    "items": [
      {
        "text": "Spending research guide",
        "link": "/research/spending"
      },
      {
        "text": "ML-DSA-44 committed-key profile",
        "link": "/research/ml-dsa-commit-profile"
      },
      {
        "text": "Construction A reference",
        "link": "/research/construction-a"
      },
      {
        "text": "Construction A security",
        "link": "/research/construction-a-security"
      },
      {
        "text": "Ownership / SIS research",
        "link": "/lean/msis-reshaping"
      },
      {
        "text": "EIP-8288 assessment",
        "link": "/research/eip-8288-summary"
      },
      {
        "text": "C13 ZK experiment",
        "link": "/research/zk-sphincs-frames"
      },
      {
        "text": "Deployment / native-key experiments",
        "link": "/research/prefix-deploy-native-keys"
      },
      {
        "text": "Classical-spend hybrid",
        "link": "/spec/classical-spend-hybrid"
      },
      {
        "text": "MLWE ownership circuit",
        "link": "/impl/noir"
      },
      {
        "text": "Pointer-signature experiment",
        "link": "/impl/pointer-signatures-poc"
      }
    ]
  },
  {
    "text": "Lean tooling and maintenance",
    "items": [
      {
        "text": "Maintainer guide",
        "link": "/lean/tooling"
      },
      {
        "text": "VCVio pin",
        "link": "/lean/vcvio-pin"
      },
      {
        "text": "Upstream work",
        "link": "/lean/vcvio-upstream"
      },
      {
        "text": "Study notes",
        "link": "/lean/lean-study-notes"
      },
      {
        "text": "Engineering lessons",
        "link": "/lean/etheorem-lessons"
      },
      {
        "text": "Historical improvement log",
        "link": "/lean/improvements"
      }
    ]
  },
  {
    "text": "Other research and history",
    "items": [
      {
        "text": "Classical comparison",
        "link": "/lean/dksap-asymmetry"
      },
      {
        "text": "Hash-based key exchange (SHA-256 / BLAKE3 commitments) as an ML-KEM alternative: why the lattice is load-bearing",
        "link": "/research/hash-based-key-exchange"
      },
      {
        "text": "After Poseidon: BLAKE2/3, Binius-era proving, and the hash policy for PQ stealth discovery",
        "link": "/research/hash-migration-blake2-binius"
      },
      {
        "text": "Keyed nonces as nullifiers (EIP-8250/8266)",
        "link": "/research/keyed-nonces-as-nullifiers"
      },
      {
        "text": "Original cohort plan (historical)",
        "link": "/research/original-project-plan"
      },
      {
        "text": "Pairwise mode: why fresh encapsulation per announcement stays",
        "link": "/research/pairwise-mode"
      },
      {
        "text": "Poseidon2 + Merkle trees + zk-STARKs for a customized registry/discovery layer",
        "link": "/research/poseidon2-stark-discovery"
      },
      {
        "text": "X-Wing as the discovery KEM: what a PQ/T hybrid buys us, and what it doesn't",
        "link": "/research/xwing-hybrid-kem"
      }
    ]
  },
  {
    "text": "Generated proof browser (all tracks)",
    "items": [
      {
        "text": "Lean proof browser",
        "link": "/lean/proofs"
      },
      {
        "text": "AnonymityFromSPR",
        "link": "/lean/proofs/anonymityfromspr"
      },
      {
        "text": "Blinding",
        "link": "/lean/proofs/blinding"
      },
      {
        "text": "BlindingEntropy",
        "link": "/lean/proofs/blindingentropy"
      },
      {
        "text": "BlindingROM",
        "link": "/lean/proofs/blindingrom"
      },
      {
        "text": "ConstructionA",
        "link": "/lean/proofs/constructiona"
      },
      {
        "text": "ConstructionASecurity",
        "link": "/lean/proofs/constructionasecurity"
      },
      {
        "text": "Controls",
        "link": "/lean/proofs/controls"
      },
      {
        "text": "Demo",
        "link": "/lean/proofs/demo"
      },
      {
        "text": "DKSAP",
        "link": "/lean/proofs/dksap"
      },
      {
        "text": "DKSAPOracle",
        "link": "/lean/proofs/dksaporacle"
      },
      {
        "text": "Games",
        "link": "/lean/proofs/games"
      },
      {
        "text": "Invariants",
        "link": "/lean/proofs/invariants"
      },
      {
        "text": "KEMAnonymity",
        "link": "/lean/proofs/kemanonymity"
      },
      {
        "text": "MLKEM",
        "link": "/lean/proofs/mlkem"
      },
      {
        "text": "MultiRecipient",
        "link": "/lean/proofs/multirecipient"
      },
      {
        "text": "MultiUnlink",
        "link": "/lean/proofs/multiunlink"
      },
      {
        "text": "Ownership",
        "link": "/lean/proofs/ownership"
      },
      {
        "text": "Reorder",
        "link": "/lean/proofs/reorder"
      },
      {
        "text": "ROMUpToBad",
        "link": "/lean/proofs/romuptobad"
      },
      {
        "text": "SharedSecretHiding",
        "link": "/lean/proofs/sharedsecrethiding"
      },
      {
        "text": "Soundness",
        "link": "/lean/proofs/soundness"
      },
      {
        "text": "SpendSecurity",
        "link": "/lean/proofs/spendsecurity"
      },
      {
        "text": "SPRTwoHop",
        "link": "/lean/proofs/sprtwohop"
      },
      {
        "text": "WidenedSigning",
        "link": "/lean/proofs/widenedsigning"
      }
    ]
  }
] as const
