// Generated by scripts/sync.mjs — do not edit.
export const generatedSidebar = [
  {
    "text": "Overview",
    "items": [
      {
        "text": "Project plan",
        "link": "/overview/plan"
      }
    ]
  },
  {
    "text": "Specification",
    "items": [
      {
        "text": "ERC draft",
        "link": "/spec/erc-draft"
      },
      {
        "text": "Technical spec",
        "link": "/spec/technical-spec"
      },
      {
        "text": "Decisions & findings (ADR log)",
        "link": "/spec/decisions"
      },
      {
        "text": "Classical-spend hybrid",
        "link": "/spec/classical-spend-hybrid"
      },
      {
        "text": "Security analysis",
        "link": "/spec/security-analysis"
      }
    ]
  },
  {
    "text": "Research",
    "items": [
      {
        "text": "ERC submission gap analysis",
        "link": "/research/erc-submission-gap-analysis"
      },
      {
        "text": "Hash-based key exchange vs ML-KEM",
        "link": "/research/hash-based-key-exchange"
      },
      {
        "text": "Hash policy after Poseidon",
        "link": "/research/hash-migration-blake2-binius"
      },
      {
        "text": "Poseidon2 + STARK discovery layer",
        "link": "/research/poseidon2-stark-discovery"
      },
      {
        "text": "X-Wing as the discovery KEM: what a PQ/T hybrid buys us, and what it doesn't",
        "link": "/research/xwing-hybrid-kem"
      }
    ]
  },
  {
    "text": "Proofs by module",
    "items": [
      {
        "text": "Lean proof browser",
        "link": "/lean/proofs"
      },
      {
        "text": "AnonymityFromSPR",
        "link": "/lean/proofs/anonymityfromspr"
      },
      {
        "text": "Blinding",
        "link": "/lean/proofs/blinding"
      },
      {
        "text": "BlindingEntropy",
        "link": "/lean/proofs/blindingentropy"
      },
      {
        "text": "BlindingROM",
        "link": "/lean/proofs/blindingrom"
      },
      {
        "text": "ConstructionA",
        "link": "/lean/proofs/constructiona"
      },
      {
        "text": "ConstructionASecurity",
        "link": "/lean/proofs/constructionasecurity"
      },
      {
        "text": "Controls",
        "link": "/lean/proofs/controls"
      },
      {
        "text": "Demo",
        "link": "/lean/proofs/demo"
      },
      {
        "text": "DKSAP",
        "link": "/lean/proofs/dksap"
      },
      {
        "text": "DKSAPOracle",
        "link": "/lean/proofs/dksaporacle"
      },
      {
        "text": "Games",
        "link": "/lean/proofs/games"
      },
      {
        "text": "Invariants",
        "link": "/lean/proofs/invariants"
      },
      {
        "text": "KEMAnonymity",
        "link": "/lean/proofs/kemanonymity"
      },
      {
        "text": "MLKEM",
        "link": "/lean/proofs/mlkem"
      },
      {
        "text": "MultiRecipient",
        "link": "/lean/proofs/multirecipient"
      },
      {
        "text": "MultiUnlink",
        "link": "/lean/proofs/multiunlink"
      },
      {
        "text": "Ownership",
        "link": "/lean/proofs/ownership"
      },
      {
        "text": "Reorder",
        "link": "/lean/proofs/reorder"
      },
      {
        "text": "ROMUpToBad",
        "link": "/lean/proofs/romuptobad"
      },
      {
        "text": "SharedSecretHiding",
        "link": "/lean/proofs/sharedsecrethiding"
      },
      {
        "text": "Soundness",
        "link": "/lean/proofs/soundness"
      },
      {
        "text": "SpendSecurity",
        "link": "/lean/proofs/spendsecurity"
      },
      {
        "text": "SPRTwoHop",
        "link": "/lean/proofs/sprtwohop"
      },
      {
        "text": "WidenedSigning",
        "link": "/lean/proofs/widenedsigning"
      }
    ]
  },
  {
    "text": "Proofs (Lean 4 / VCVio)",
    "items": [
      {
        "text": "Overview",
        "link": "/lean"
      },
      {
        "text": "The announcement model",
        "link": "/lean/announcement-model"
      },
      {
        "text": "DKSAP asymmetry",
        "link": "/lean/dksap-asymmetry"
      },
      {
        "text": "Encodings",
        "link": "/lean/encodings"
      },
      {
        "text": "Lessons from etheorem",
        "link": "/lean/etheorem-lessons"
      },
      {
        "text": "Proposed improvements",
        "link": "/lean/improvements"
      },
      {
        "text": "Lean 4 study notes",
        "link": "/lean/lean-study-notes"
      },
      {
        "text": "Spend forgery as MSIS",
        "link": "/lean/msis-reshaping"
      },
      {
        "text": "KEM anonymity from SPR",
        "link": "/lean/spr-two-hop"
      },
      {
        "text": "Tracking the VCVio pin",
        "link": "/lean/vcvio-pin"
      },
      {
        "text": "VCVio upstream findings",
        "link": "/lean/vcvio-upstream"
      }
    ]
  },
  {
    "text": "Implementations",
    "items": [
      {
        "text": "Python executable spec",
        "link": "/impl/python"
      },
      {
        "text": "TypeScript scanning client",
        "link": "/impl/js-client"
      },
      {
        "text": "Noir ownership circuit",
        "link": "/impl/noir"
      },
      {
        "text": "POC: (v, r, s) as pointers",
        "link": "/impl/pointer-signatures-poc"
      }
    ]
  }
] as const
