#!/usr/bin/env python3
"""Replay python/vectors/v0/vectors.json through the Lean contract model.

Writes StealthKeyExchange/Vectors.lean: one build-checked `#guard` per vector
case (and per recipient), stating what the contract does with that announcement
or meta-address. The bytes' CONTENT never reaches the contract — only lengths,
the version byte and the address do — so the generated file carries lengths,
not the 1 kB ciphertexts. Two things are pinned:

  * completeness: every case the scanner accepts (`expect == "match"`) is
    accepted on-chain, so the wire layer never blocks a genuine payment;
  * the wire/scanner split: a negative case is rejected on-chain exactly when it
    is malformed on the wire (here: the truncated ciphertext), and passes
    otherwise (wrong view tag, bit flip — only a scanner can tell).

Usage: python3 gen_vectors.py            # rewrite Vectors.lean
       python3 gen_vectors.py --check    # exit 1 if Vectors.lean is stale
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
VECTORS = ROOT / "python" / "vectors" / "v0" / "vectors.json"
OUT = HERE.parent / "StealthKeyExchange" / "Vectors.lean"


def hexlen(s: str) -> int:
    return len(s.removeprefix("0x")) // 2


def render(v: dict) -> str:
    ct_bytes = v["sizes"]["ephemeral_pub_key"]
    tag_bytes = v["view_tag_bytes"]
    lines = [
        "import StealthKeyExchange.Contract",
        "",
        "/-!",
        "# The conformance vectors, replayed through the model",
        "",
        f"GENERATED by `scripts/gen_vectors.py` from `python/vectors/v0/vectors.json`",
        f'(schema `{v["schema"]}`, params `{v["params"]}`) — do not edit; CI regenerates',
        "and diffs. Every `#guard` is checked by the build. Only lengths, version bytes",
        "and addresses appear: that is all the contract reads of an announcement.",
        "-/",
        "",
        "namespace StealthKeyExchange.Vectors",
        "",
        "/-- A fresh deployment at address `1`: no keys, an empty announcer log. -/",
        "def s0 : State := { self := 1, keys := #[], log := [] }",
        "",
        "/-- A ciphertext, view tag or key of the given length (content is irrelevant on-chain). -/",
        "def zeros (n : Nat) : Bytes := List.replicate n 0",
        "",
        "/-! ## Declared sizes -/",
        "",
        f"#guard schemeId = {v['scheme_id']}",
        f"#guard viewTagBytes = {tag_bytes}",
        f"#guard Kem.mlkem768.metaAddressBytes = {v['sizes']['meta_address']}",
        f"#guard Kem.mlkem768.ciphertextBytes = {ct_bytes}",
        "",
        "/-! ## Recipients: meta-addresses type as ML-KEM-768, their keys register -/",
        "",
    ]
    idx = 0
    for name, r in v["recipients"].items():
        meta = r["meta_address"]
        mlen, version = hexlen(meta), int(meta[2:4], 16)
        ek_len = mlen - 1 - 32 - 4416
        lines += [
            f"-- recipient {name}: meta-address {mlen} B, version 0x{version:02x}; ek = the last {ek_len} B",
            f"#guard kemOfMetaAddress (0x{version:02x} :: zeros {mlen - 1}) = .ok .mlkem768",
            f"#guard kemOfEncapsulationKeyLength {ek_len} = some .mlkem768",
            f"#guard (registerViewingKey s0 (zeros {ek_len})).toBool = true",
            "",
        ]
        idx += 1
    lines += [
        "/-- Registering the recipients' keys in order assigns indices 0, 1, … and reads back. -/",
        "def registered : Except Error State := do",
    ]
    lines.append("  let s := s0")
    for i, (name, r) in enumerate(v["recipients"].items()):
        ek_len = hexlen(r["meta_address"]) - 1 - 32 - 4416
        lines.append(f"  let (i{i}, s) ← registerViewingKey s (zeros {ek_len})")
        lines.append(f"  if i{i} ≠ {i} then throw (.noSuchViewingKey i{i})")
    lines.append("  pure s")
    lines += ["", f"#guard registered.toBool = true"]
    for i, (name, r) in enumerate(v["recipients"].items()):
        ek_len = hexlen(r["meta_address"]) - 1 - 32 - 4416
        lines.append(
            f"#guard (registered >>= fun s => viewingKeyOf s {i}) = .ok {{ kem := .mlkem768, ek := zeros {ek_len} }}")
    lines.append(f"#guard (registered.map viewingKeyCount) = .ok {len(v['recipients'])}")
    lines += ["", "/-! ## Cases: what `announce` does with each announcement -/", ""]
    for c in v["cases"]:
        a = c["announcement"]
        ct_len, tag_len = hexlen(a["ephemeral_pub_key"]), hexlen(a["view_tag"])
        addr = int(a["stealth_address"], 16)
        onchain = ct_len == ct_bytes and tag_len >= tag_bytes
        if c["expect"] in ("match", "valid_proof") and not onchain:
            sys.exit(f"{c['name']}: scanner accepts but the contract would reject — wire layer blocks a payment")
        verdict = "accepted" if onchain else "REJECTED"
        lines += [
            f"-- {c['name']}: ct {ct_len} B, view tag {tag_len} B; scanner: {c['expect']}; on-chain: {verdict}",
            f"#guard (announce s0 {addr:#x} (zeros {ct_len}) (zeros {tag_len})).toBool = {'true' if onchain else 'false'}",
        ]
        if onchain:
            lines.append(
                f"#guard announce s0 {addr:#x} (zeros {ct_len}) (zeros {tag_len}) = "
                f".ok (.mlkem768, {{ s0 with log := [forwarded s0 {addr:#x} (zeros {ct_len}) (zeros {tag_len})] }})")
        else:
            lines.append(
                f"#guard announce s0 {addr:#x} (zeros {ct_len}) (zeros {tag_len}) = "
                f".error (.unsupportedCiphertextLength {ct_len})")
        lines.append("")
    lines += ["end StealthKeyExchange.Vectors", ""]
    return "\n".join(lines)


def main() -> int:
    text = render(json.loads(VECTORS.read_text()))
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
