import StealthKeyExchange.Contract

/-!
# The conformance vectors, replayed through the model

GENERATED by `scripts/gen_vectors.py` from `python/vectors/v0/vectors.json`
(schema `v0`, params `ML-KEM-768+ML-DSA-65`) and `commit_vectors.json`
(schema `v0`, format 0x02) — do not edit; CI regenerates
and diffs. Every `#guard` is checked by the build. Only lengths, version bytes
and addresses appear: that is all the contract reads of an announcement.
-/

namespace StealthKeyExchange.Vectors

/-- A fresh deployment at address `1`: no keys, an empty announcer log. -/
def s0 : State := { self := 1, keys := #[], log := [] }

/-- A ciphertext, view tag or key of the given length (content is irrelevant on-chain). -/
def zeros (n : Nat) : Bytes := List.replicate n 0

/-! ## Declared sizes -/

#guard schemeId = 2
#guard viewTagBytes = 1
#guard Kem.mlkem768.metaAddressBytes .constructionA = 5633
#guard Kem.mlkem768.metaAddressBytes .commit = 1217
#guard Kem.mlkem768.ciphertextBytes = 1088

/-! ## Recipients: meta-addresses type as ML-KEM-768, their keys register -/

-- recipient A: meta-address 5633 B, version 0x01; ek = the last 1184 B
#guard kemOfMetaAddress (0x01 :: zeros 5632) = .ok (.mlkem768, .constructionA)
#guard kemOfEncapsulationKeyLength 1184 = some .mlkem768
#guard (registerViewingKey s0 (zeros 1184)).toBool = true

-- recipient B: meta-address 5633 B, version 0x01; ek = the last 1184 B
#guard kemOfMetaAddress (0x01 :: zeros 5632) = .ok (.mlkem768, .constructionA)
#guard kemOfEncapsulationKeyLength 1184 = some .mlkem768
#guard (registerViewingKey s0 (zeros 1184)).toBool = true

/-- Registering the recipients' keys in order assigns indices 0, 1, … and reads back. -/
def registered : Except Error State := do
  let s := s0
  let (i0, s) ← registerViewingKey s (zeros 1184)
  if i0 ≠ 0 then throw (.noSuchViewingKey i0)
  let (i1, s) ← registerViewingKey s (zeros 1184)
  if i1 ≠ 1 then throw (.noSuchViewingKey i1)
  pure s

#guard registered.toBool = true
#guard (registered >>= fun s => viewingKeyOf s 0) = .ok { kem := .mlkem768, ek := zeros 1184 }
#guard (registered >>= fun s => viewingKeyOf s 1) = .ok { kem := .mlkem768, ek := zeros 1184 }
#guard (registered.map viewingKeyCount) = .ok 2

/-! ## Commitment meta-addresses (format 0x02, D-024): typed by layout and length -/

-- commitment recipient a: meta-address 1217 B, version 0x02; ek = the last 1184 B
#guard kemOfMetaAddress (0x02 :: zeros 1216) = .ok (.mlkem768, .commit)
#guard kemOfEncapsulationKeyLength 1184 = some .mlkem768
-- commitment recipient b: meta-address 1217 B, version 0x02; ek = the last 1184 B
#guard kemOfMetaAddress (0x02 :: zeros 1216) = .ok (.mlkem768, .commit)
#guard kemOfEncapsulationKeyLength 1184 = some .mlkem768
-- commitment recipient c: meta-address 1217 B, version 0x02; ek = the last 1184 B
#guard kemOfMetaAddress (0x02 :: zeros 1216) = .ok (.mlkem768, .commit)
#guard kemOfEncapsulationKeyLength 1184 = some .mlkem768

-- the two layouts never confuse each other: a commitment length under the Construction A byte,
-- or a Construction A length under the commitment byte, is rejected
#guard kemOfMetaAddress (0x01 :: zeros 1216) = .error (.unsupportedMetaAddress 1217 0x01)
#guard kemOfMetaAddress (0x02 :: zeros 5632) = .error (.unsupportedMetaAddress 5633 0x02)

/-! ## Cases: what `announce` does with each announcement -/

-- v0 positive/basic-match: ct 1088 B, view tag 1 B; scanner: match; on-chain: accepted
#guard (announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)] })

-- v0 positive/second-payment-unlinkable: ct 1088 B, view tag 1 B; scanner: match; on-chain: accepted
#guard (announce s0 0x2e34775b59da7b27af70484d423b11b480fd874 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x2e34775b59da7b27af70484d423b11b480fd874 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x2e34775b59da7b27af70484d423b11b480fd874 (zeros 1088) (zeros 1)] })

-- v0 negative/wrong-view-tag: ct 1088 B, view tag 1 B; scanner: no_match; on-chain: accepted
#guard (announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)] })

-- v0 negative/wrong-recipient: ct 1088 B, view tag 1 B; scanner: no_match; on-chain: accepted
#guard (announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)] })

-- v0 negative/truncated-ciphertext: ct 1087 B, view tag 1 B; scanner: no_match; on-chain: REJECTED
#guard (announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1087) (zeros 1)).toBool = false
#guard announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1087) (zeros 1) = .error (.unsupportedCiphertextLength 1087)

-- v0 negative/bitflipped-ciphertext: ct 1088 B, view tag 1 B; scanner: no_match; on-chain: accepted
#guard (announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)] })

-- v0 possession/deterministic-proof: ct 1088 B, view tag 1 B; scanner: valid_proof; on-chain: accepted
#guard (announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)] })

-- commit a-1: ct 1088 B, view tag 1 B; scanner: match; on-chain: accepted
#guard (announce s0 0xaa7694f11496e669970e0d26396d29ba3eb7107c (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0xaa7694f11496e669970e0d26396d29ba3eb7107c (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0xaa7694f11496e669970e0d26396d29ba3eb7107c (zeros 1088) (zeros 1)] })

-- commit a-2: ct 1088 B, view tag 1 B; scanner: match; on-chain: accepted
#guard (announce s0 0x4bf7771fb1de5fd345b19d7a41fac9d80e6e54c0 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x4bf7771fb1de5fd345b19d7a41fac9d80e6e54c0 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x4bf7771fb1de5fd345b19d7a41fac9d80e6e54c0 (zeros 1088) (zeros 1)] })

-- commit b-1: ct 1088 B, view tag 1 B; scanner: match; on-chain: accepted
#guard (announce s0 0xdfa48d6a8a454fd39e1d114432d7f6471d5410d6 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0xdfa48d6a8a454fd39e1d114432d7f6471d5410d6 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0xdfa48d6a8a454fd39e1d114432d7f6471d5410d6 (zeros 1088) (zeros 1)] })

-- commit c-1: ct 1088 B, view tag 1 B; scanner: match; on-chain: accepted
#guard (announce s0 0x7b92272fa4496199726b4b21ed7a56c9cd44d44e (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x7b92272fa4496199726b4b21ed7a56c9cd44d44e (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x7b92272fa4496199726b4b21ed7a56c9cd44d44e (zeros 1088) (zeros 1)] })

-- commit a-1-seen-by-b: ct 1088 B, view tag 1 B; scanner: no_match; on-chain: accepted
#guard (announce s0 0xaa7694f11496e669970e0d26396d29ba3eb7107c (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0xaa7694f11496e669970e0d26396d29ba3eb7107c (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0xaa7694f11496e669970e0d26396d29ba3eb7107c (zeros 1088) (zeros 1)] })

end StealthKeyExchange.Vectors
