import StealthKeyExchange.Contract

/-!
# The conformance vectors, replayed through the model

GENERATED by `scripts/gen_vectors.py` from `python/vectors/v0/vectors.json`
(schema `v0`, params `ML-KEM-768+ML-DSA-65`) — do not edit; CI regenerates
and diffs. Every `#guard` is checked by the build. Only lengths, version bytes
and addresses appear: that is all the contract reads of an announcement.
-/

namespace StealthKeyExchange.Vectors

/-- A fresh deployment at address `1`: no keys, an empty announcer log. -/
def s0 : State := { self := 1, keys := #[], log := [] }

/-- A ciphertext, view tag or key of the given length (content is irrelevant on-chain). -/
def zeros (n : Nat) : Bytes := List.replicate n 0

/-! ## Declared sizes -/

#guard schemeId = 2
#guard viewTagBytes = 1
#guard Kem.mlkem768.metaAddressBytes = 5633
#guard Kem.mlkem768.ciphertextBytes = 1088

/-! ## Recipients: meta-addresses type as ML-KEM-768, their keys register -/

-- recipient A: meta-address 5633 B, version 0x01; ek = the last 1184 B
#guard kemOfMetaAddress (0x01 :: zeros 5632) = .ok .mlkem768
#guard kemOfEncapsulationKeyLength 1184 = some .mlkem768
#guard (registerViewingKey s0 (zeros 1184)).toBool = true

-- recipient B: meta-address 5633 B, version 0x01; ek = the last 1184 B
#guard kemOfMetaAddress (0x01 :: zeros 5632) = .ok .mlkem768
#guard kemOfEncapsulationKeyLength 1184 = some .mlkem768
#guard (registerViewingKey s0 (zeros 1184)).toBool = true

/-- Registering the recipients' keys in order assigns indices 0, 1, … and reads back. -/
def registered : Except Error State := do
  let s := s0
  let (i0, s) ← registerViewingKey s (zeros 1184)
  if i0 ≠ 0 then throw (.noSuchViewingKey i0)
  let (i1, s) ← registerViewingKey s (zeros 1184)
  if i1 ≠ 1 then throw (.noSuchViewingKey i1)
  pure s

#guard registered.toBool = true
#guard (registered >>= fun s => viewingKeyOf s 0) = .ok { kem := .mlkem768, ek := zeros 1184 }
#guard (registered >>= fun s => viewingKeyOf s 1) = .ok { kem := .mlkem768, ek := zeros 1184 }
#guard (registered.map viewingKeyCount) = .ok 2

/-! ## Cases: what `announce` does with each announcement -/

-- positive/basic-match: ct 1088 B, view tag 1 B; scanner: match; on-chain: accepted
#guard (announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)] })

-- positive/second-payment-unlinkable: ct 1088 B, view tag 1 B; scanner: match; on-chain: accepted
#guard (announce s0 0x2e34775b59da7b27af70484d423b11b480fd874 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x2e34775b59da7b27af70484d423b11b480fd874 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x2e34775b59da7b27af70484d423b11b480fd874 (zeros 1088) (zeros 1)] })

-- negative/wrong-view-tag: ct 1088 B, view tag 1 B; scanner: no_match; on-chain: accepted
#guard (announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)] })

-- negative/wrong-recipient: ct 1088 B, view tag 1 B; scanner: no_match; on-chain: accepted
#guard (announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)] })

-- negative/truncated-ciphertext: ct 1087 B, view tag 1 B; scanner: no_match; on-chain: REJECTED
#guard (announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1087) (zeros 1)).toBool = false
#guard announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1087) (zeros 1) = .error (.unsupportedCiphertextLength 1087)

-- negative/bitflipped-ciphertext: ct 1088 B, view tag 1 B; scanner: no_match; on-chain: accepted
#guard (announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)] })

-- possession/deterministic-proof: ct 1088 B, view tag 1 B; scanner: valid_proof; on-chain: accepted
#guard (announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)).toBool = true
#guard announce s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1) = .ok (.mlkem768, { s0 with log := [forwarded s0 0x40bae0a40e9fbbe4d9a530b3c55994603bf5ceb7 (zeros 1088) (zeros 1)] })

end StealthKeyExchange.Vectors
